services:
  web:
    build: .
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./services/web/:/usr/src/app/
      - store:/store/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev

volumes:
  store: